classifiers = {
    'grasr': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k31r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k32r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k33r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k34r': {
        'axelrod-python_class': 'Grudger',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k35r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k36r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k37r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k38r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k39r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k40r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k41r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k42r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k43r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k44r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k45r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k46r': {
        'axelrod-python_class': 'Eatherley',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k47r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k48r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k49r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k50r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k51r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k52r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k53r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k54r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k55r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k56r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k57r': {
        'axelrod-python_class': 'Nydegger',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k58r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k59r': {
        'axelrod-python_class': 'RevisedDowning',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k60r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k61r': {
        'axelrod-python_class': 'Champion',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k62r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k63r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k64r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k65r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k66r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k67r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k68r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k69r': {
        'axelrod-python_class': 'Joss',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k70r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k71r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k72r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k73r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k74r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k74rxx': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k75r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k76r': {
        'axelrod-python_class': 'Tester',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k77r': {
        'axelrod-python_class': 'Feld',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k78r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k79r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k80r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k81r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k82r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k83r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k84r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k85r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k86r': {
        'axelrod-python_class': 'Grofman',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k87r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k88r': {
        'axelrod-python_class': None,
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'k89r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k90r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k91r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k92r': {
        'axelrod-python_class': None,
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'k93r': {
        'axelrod-python_class': 'UnnamedStrategy',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'kpavlovc': {
        'axelrod-python_class': 'WinStayLoseShift',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'krandomc': {
        'axelrod-python_class': 'Random',
        'stochastic': True,
        'author': None,
        'original_rank': None},
    'ktf2tc': {
        'axelrod-python_class': 'TitFor2Tats',
        'stochastic': False,
        'author': None,
        'original_rank': None},
    'ktitfortatc': {
        'axelrod-python_class': 'TitForTat',
        'stochastic': False,
        'author': None,
        'original_rank': None},
}

all_strategies = classifiers.keys()
